[package]
name = "example_stubs"
version = "0.1.0"
authors = ["joris giovannangeli <joris.giovannangeli@ahrefs.com>"]

[dependencies]
ocaml = "0.5.1"

[dependencies.derive-ocaml]
path = ".."
features = ["stubs", "derive"]

[lib]
crate-type = ["staticlib"]
